"""reviewed course claim evidence

Revision ID: 169d54a90cfc
Revises: 8a9606141a32
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "169d54a90cfc"
down_revision = "8a9606141a32"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_facts",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("raw_value", sa.Integer(), nullable=False),
        sa.Column("raw_unit", sa.String(), nullable=False),
        sa.Column("factor", sa.Integer(), nullable=False),
        sa.Column("normalized_value", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("reviewer", sa.String(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('tuition', 'duration')", name=op.f("ck_course_facts_kind")),
        sa.CheckConstraint("factor > 0", name=op.f("ck_course_facts_factor")),
        sa.CheckConstraint(
            "raw_value >= 0 AND normalized_value >= 0", name=op.f("ck_course_facts_values")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_facts_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_sources.id"], name=op.f("fk_course_facts_source_id_data_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_facts")),
        sa.UniqueConstraint("course_id", "kind", name="uq_course_fact_kind"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course_facts")
    # ### end Alembic commands ###
