"""initial redesigned college workspace

Revision ID: 8a9606141a32
Revises:
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "8a9606141a32"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("reporting_year", sa.Integer(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status != 'verified' OR (url IS NOT NULL AND verified_at IS NOT NULL)",
            name=op.f("ck_data_sources_verified_evidence"),
        ),
        sa.CheckConstraint(
            "status IN ('demo', 'unverified', 'verified')", name=op.f("ck_data_sources_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "colleges",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("established", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image", sa.String(), server_default="", nullable=False),
        sa.Column("accreditation", sa.String(), server_default="", nullable=False),
        sa.Column("facilities", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_sources.id"], name=op.f("fk_colleges_source_id_data_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_colleges")),
        sa.UniqueConstraint("slug", name=op.f("uq_colleges_slug")),
    )
    op.create_index(op.f("ix_colleges_state"), "colleges", ["state"], unique=False)
    op.create_index(op.f("ix_colleges_type"), "colleges", ["type"], unique=False)
    op.create_table(
        "student_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_student_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_student_profiles")),
    )
    op.create_table(
        "workspace_imports",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Uuid(), nullable=False),
        sa.Column("payload_hash", sa.String(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_imports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_imports")),
        sa.UniqueConstraint("user_id", "key", name="uq_workspace_import_key"),
    )
    op.create_index(
        op.f("ix_workspace_imports_user_id"), "workspace_imports", ["user_id"], unique=False
    )
    op.create_table(
        "college_metrics",
        sa.Column("college_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_college_metrics_nonnegative")),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["colleges.id"],
            name=op.f("fk_college_metrics_college_id_colleges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_college_metrics_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_college_metrics")),
        sa.UniqueConstraint("college_id", "kind", name="uq_college_metric_kind"),
    )
    op.create_index(
        op.f("ix_college_metrics_college_id"), "college_metrics", ["college_id"], unique=False
    )
    op.create_table(
        "courses",
        sa.Column("college_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("degree", sa.String(), nullable=False),
        sa.Column("duration_months", sa.Integer(), nullable=False),
        sa.Column("annual_tuition", sa.Integer(), nullable=True),
        sa.Column("fee_basis", sa.String(), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "fee_basis IN ('demo-assumption', 'reported', 'unknown')",
            name=op.f("ck_courses_fee_basis"),
        ),
        sa.CheckConstraint(
            "annual_tuition IS NULL OR annual_tuition >= 0", name=op.f("ck_courses_tuition")
        ),
        sa.CheckConstraint("duration_months > 0", name=op.f("ck_courses_duration")),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["colleges.id"],
            name=op.f("fk_courses_college_id_colleges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_sources.id"], name=op.f("fk_courses_source_id_data_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
        sa.UniqueConstraint("id", "college_id", name="uq_course_college_pair"),
    )
    op.create_index(op.f("ix_courses_annual_tuition"), "courses", ["annual_tuition"], unique=False)
    op.create_index(op.f("ix_courses_college_id"), "courses", ["college_id"], unique=False)
    op.create_index(op.f("ix_courses_degree"), "courses", ["degree"], unique=False)
    op.create_table(
        "workspace_entries",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("college_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("stage", sa.String(), server_default="Researching", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("next_action", sa.String(), server_default="", nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("scenario", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage IN ('Researching', 'Shortlisted', 'Applying', 'Applied', "
            "'Offer received', 'Waitlisted', 'Rejected', 'Withdrawn')",
            name=op.f("ck_workspace_entries_stage"),
        ),
        sa.CheckConstraint("revision > 0", name=op.f("ck_workspace_entries_revision")),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["colleges.id"],
            name=op.f("fk_workspace_entries_college_id_colleges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id", "college_id"],
            ["courses.id", "courses.college_id"],
            name="fk_workspace_course_college",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_entries")),
        sa.UniqueConstraint(
            "user_id",
            "college_id",
            "course_id",
            name="uq_workspace_user_option",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_workspace_entries_college_id"), "workspace_entries", ["college_id"], unique=False
    )
    op.create_index(
        op.f("ix_workspace_entries_user_id"), "workspace_entries", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspace_entries_user_id"), table_name="workspace_entries")
    op.drop_index(op.f("ix_workspace_entries_college_id"), table_name="workspace_entries")
    op.drop_table("workspace_entries")
    op.drop_index(op.f("ix_courses_degree"), table_name="courses")
    op.drop_index(op.f("ix_courses_college_id"), table_name="courses")
    op.drop_index(op.f("ix_courses_annual_tuition"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_college_metrics_college_id"), table_name="college_metrics")
    op.drop_table("college_metrics")
    op.drop_index(op.f("ix_workspace_imports_user_id"), table_name="workspace_imports")
    op.drop_table("workspace_imports")
    op.drop_table("student_profiles")
    op.drop_index(op.f("ix_colleges_type"), table_name="colleges")
    op.drop_index(op.f("ix_colleges_state"), table_name="colleges")
    op.drop_table("colleges")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
